package com.tradingbot.model;

import com.tradingbot.model.enums.BookType;
import com.tradingbot.model.enums.OrderType;
import com.tradingbot.model.enums.ProductType;
import com.tradingbot.model.enums.SignalType;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Represents a trading signal generated by a strategy, containing all details needed to place an order.
 */
public record Signal(
    String strategyId,
    String targetAccountId,
    String symbol,
    String exchange,
    SignalType signalType,
    int quantity,
    BigDecimal price,
    BigDecimal triggerPrice,
    OrderType orderType,
    ProductType productType,
    BookType bookType,
    String tag,
    Instant timestamp
) {
    /**
     * Creates a new {@link Builder} for constructing {@link Signal} instances.
     *
     * @return a new Builder instance
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Fluent builder for constructing {@link Signal} instances.
     */
    public static class Builder {
        private String strategyId;
        private String targetAccountId;
        private String symbol;
        private String exchange = "NFO";
        private SignalType signalType;
        private int quantity;
        private BigDecimal price;
        private BigDecimal triggerPrice;
        private OrderType orderType = OrderType.LIMIT;
        private ProductType productType = ProductType.MIS;
        private BookType bookType = BookType.INTRADAY;
        private String tag;
        private Instant timestamp;

        /** Sets the strategy ID that generated the signal. */
        public Builder strategyId(String strategyId) { this.strategyId = strategyId; return this; }
        /** Sets the target account ID to execute the signal in. */
        public Builder targetAccountId(String targetAccountId) { this.targetAccountId = targetAccountId; return this; }
        /** Sets the trading symbol. */
        public Builder symbol(String symbol) { this.symbol = symbol; return this; }
        /** Sets the exchange (defaults to "NFO"). */
        public Builder exchange(String exchange) { this.exchange = exchange; return this; }
        /** Sets the signal type (e.g. BUY, SELL). */
        public Builder signalType(SignalType signalType) { this.signalType = signalType; return this; }
        /** Sets the order quantity. */
        public Builder quantity(int quantity) { this.quantity = quantity; return this; }
        /** Sets the limit price for the order. */
        public Builder price(BigDecimal price) { this.price = price; return this; }
        /** Sets the trigger price for stop-loss orders. */
        public Builder triggerPrice(BigDecimal triggerPrice) { this.triggerPrice = triggerPrice; return this; }
        /** Sets the order type (e.g. LIMIT, MARKET, SL, SL-M). */
        public Builder orderType(OrderType orderType) { this.orderType = orderType; return this; }
        /** Sets the product type (e.g. MIS, CNC, NRML). */
        public Builder productType(ProductType productType) { this.productType = productType; return this; }
        /** Sets the book type (e.g. INTRADAY, CARRYFORWARD). */
        public Builder bookType(BookType bookType) { this.bookType = bookType; return this; }
        /** Sets a user-defined tag for signal identification. */
        public Builder tag(String tag) { this.tag = tag; return this; }
        /** Sets the signal generation timestamp. */
        public Builder timestamp(Instant timestamp) { this.timestamp = timestamp; return this; }

        /**
         * Builds and returns the {@link Signal} instance.
         * If {@code timestamp} is not set, it defaults to the current time.
         *
         * @return a new Signal with the configured values
         */
        public Signal build() {
            return new Signal(strategyId, targetAccountId, symbol, exchange, signalType, quantity, price, triggerPrice, orderType, productType, bookType, tag, timestamp != null ? timestamp : Instant.now());
        }
    }
}
