package com.tradingbot.model.enums;

/**
 * Represents the type of trading signal generated by a strategy.
 */
public enum SignalType {
    /** Signal to enter a new long (buy) position. */
    ENTRY_LONG,
    /** Signal to enter a new short (sell) position. */
    ENTRY_SHORT,
    /** Signal to exit an existing long position completely. */
    EXIT_LONG,
    /** Signal to exit an existing short position completely. */
    EXIT_SHORT,
    /** Signal to partially exit an existing long position. */
    EXIT_PARTIAL_LONG,
    /** Signal to partially exit an existing short position. */
    EXIT_PARTIAL_SHORT,
    /** Signal to cancel a pending or open order. */
    CANCEL
}
